CoshiMediaBundle_index:
    pattern:  /
    defaults: { _controller: CoshiMediaBundle:Backend:index }

CoshiMediaBundle_upload:
    pattern:  /create
    defaults: { _controller: CoshiMediaBundle:Backend:upload }

CoshiMediaBundle_delete:
    pattern: /delete/{id}
    defaults: { _controller: CoshiMediaBundle:Backend:delete }

coshi_media_internal_list:
    pattern: /internal/list/{element}
    defaults: {_controller: 'coshi_media.controller_internal:listAction'}
