parameters:

    coshi_media: 
        linkmap: 
            "Sylius\\Sandbox\\Bundle\\AssortmentBundle\\Entity\\Product": "Coshi\\MediaBundle\\Entity\\ProductMedia"
        uploader:
            media_path: uploads
            www_root: public
        imager:
            options:
                lib: gd
                thumbnails: 
                    small: { width: 128, height: 128, dir: 't1' }
services:
#    coshi_media.example:
#        class: %coshi_media.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    coshi_media.imager:
        class: Coshi\MediaBundle\Service\Imager
        arguments: [%coshi_media%]
        
    coshi_media.media_manager:
        class: Coshi\MediaBundle\Manager\MediaManager
        arguments: [@doctrine.orm.default_entity_manager,@coshi_media.imager,%coshi_media%]
        calls:
            - [setKernel , [@kernel]]
            - [setContainer, [@service_container]]
    
    coshi_media.thumbnail_extension:
        class: Coshi\MediaBundle\Templating\ThumbnailExtension
        calls:
            - [setOptions, [%coshi_media%]]
        tags:
            - { name: twig.extension }
    coshi_media.controller_internal:
        class: Coshi\MediaBundle\Controller\InternalController
        calls: 
            - [setContainer, [@service_container ]]
            - [setMediaService, [@coshi_media.media_manager]]
            - [setEntityManager, [@doctrine.orm.default_entity_manager]]
        
